/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EIOSIAD_AUTODEFS_H
#define S3EIOSIAD_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_IOSIAD_NAME "s3eIOSIAd"
#define S3E_EXT_IOSIAD_HASH 0xb2e1d429

#endif /* !S3EIOSIAD_AUTODEFS_H */
